spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ewm_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update

stats-server.url=${STATS_SERVER_URL:http://localhost:9090}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss